# Generated by Django 3.1.3 on 2020-11-26 02:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_images_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 2, 31, 25, 879624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='images',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
