# Generated by Django 3.1.3 on 2020-11-26 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201126_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 2, 32, 21, 81920, tzinfo=utc)),
        ),
    ]
