# Generated by Django 3.1.3 on 2020-11-26 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201126_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 2, 33, 24, 770132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
