# Generated by Django 3.1.3 on 2020-11-26 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201126_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 2, 34, 3, 222203, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
